[project]
name = "transformar_fact"
version = "0.0.1"
description = "CLI para transformar_fact de id_establecimiento"
authors = [{name="Renato"},{name="Leo"}]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "rich",
]

[project.scripts]
transformar_fact = "transformar_fact.cli:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {""="src"}

[tool.setuptools.packages.find]
where = ["src"]
